// src/types/index.ts
export type LegalType = "privacy" | "terms";
export type AuthView = "login" | "trial" | "register" | "forgot";
export type PublicView = "landing" | "features" | "pricing" | "comparison" | "contact" | "product-lite" | "product-pro" | "product-full" | "auth";
export type MarketingTheme = "elegant" | "futuristic";
export type AppView = "mywork" | "dashboard" | "leads" | "pipeline" | "followups" | "revenue" | "invoices" | "sources" | "users";
export type UsersTab = "licensees" | "tenant-users" | "platform-controls";
export type UserRole = "owner" | "admin" | "sales";
export type ProductMode = "lite" | "pro" | "full";
export type BillingCycle = "monthly" | "quarterly" | "annual";
export type SubscriptionStatus = "active" | "renewal_due" | "grace" | "suspended" | "cancelled";
export type BillingRecordStatus = "pending" | "paid" | "failed" | "cancelled";
export type BillingRecordType = "renewal" | "upgrade" | "downgrade";
export type AccessScope = "all" | "assigned" | "none";
export type StaffProfile = "sales" | "followup" | "collections" | "operations";
export type MonthRangePreset = "1" | "3" | "6" | "12" | "custom";
export type ForecastMode = "unweighted" | "weighted";
export type DashboardDateScope = "today" | "yesterday" | "last7" | "last30" | "mtd" | "qtd" | "lastMonth" | "all" | "custom";
export type PlanPresetKey = "starter" | "growth" | "scale" | "enterprise";
export type CreateLicenseePlanChoice = "custom" | string;
export type LicenseTermPreset = "annual" | "trial15";
export type PipelineSort = "priority" | "value" | "expected" | "followup" | "age";
export type PipelineWipScope = "today" | "custom" | "all";
export type FollowupQueue = "all" | "overdue" | "today" | "upcoming" | "no-date";
export type FollowupBulkAction = "" | "mark-done" | "move-today" | "snooze-2" | "snooze-7" | "reassign" | "set-date";
export type LeadBulkAction = "" | "mark-done" | "snooze-2" | "move-contacted" | "reassign";
export type ModuleMode = "basic" | "advanced";
export type RevenueTab = "overview" | "forecast" | "collections" | "reconciliation" | "exports";
export type LeadOptionalColumn = "source" | "service" | "temperature" | "deal" | "expected" | "invoice" | "tag";
export type InvoiceWorkspaceTab = "workspace" | "collections-inbox" | "client-master";
export type CollectionsChannel = "email" | "whatsapp" | "both";
export type WhatsAppProvider = "meta-cloud" | "twilio" | "gupshup" | "interakt" | "custom-webhook";
export type CollectionsDispatchStatus = "queued" | "sent" | "delivered" | "read" | "failed";
export type BeforeInstallPromptEvent = Event & {
  prompt: () => Promise<void>;
  userChoice: Promise<{ outcome: "accepted" | "dismissed"; platform: string }>;
};
export type CaptureSummaryItem = {
  field: string;
  value: string;
  confidence: "High" | "Review";
};
